### ISSUE TITLE
Multiple adBreaks spec

### ISSUE THREAD

**Issue by ksheurs** [rokudev/feed-specifications#5]
In the Direct Publisher Spec, the `adBreaks` field says "One or more time codes. Represents a time duration from the beginning of the video where an ad shows up. Conforms to the format: {hh}:{mm}:{ss}".

For this `string` type, what's the recommended structure for adding multiple?

**Comment by mmarlett** [comment]
They are just comma separated, but each one needs to be in quotes. So the JSON would look like this: 

adBreaks":["00:00:00","00:00:52"]

**Comment by ksheurs** [comment]
Got it OK, thanks! The `type`: `string` reference for `adBreaks` in https://github.com/rokudev/feed-specifications/blob/master/direct-publisher-feed-specification.md is a little confusing then. Should maybe note that it can be a `string` or an `array` of `strings`.
